source 'https://gitlab.lifesense.com/commonlib_ios/CocoaPodsSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'LSNetworkingModule_Example' do
  pod 'LSNetworkingModule', :path => '../'

  target 'LSNetworkingModule_Tests' do
    inherit! :search_paths

    
  end
end
